/** @jest-environment jsdom */
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import NewslettersPage from '../page';
jest.mock('@/components/Toast',()=>({__esModule:true,default:({message}:{message:string})=><div role="status">{message}</div>}));
jest.mock('@/components/ConfirmDialog',()=>({__esModule:true,default:({open,onConfirm,confirmLabel,message}:{open:boolean;onConfirm:()=>void;confirmLabel:string;message:string})=>open?<div>{message}<button onClick={onConfirm}>{confirmLabel}</button></div>:null}));
const mockFetch=jest.fn();global.fetch=mockFetch;
const id='e1000000-0000-4000-8000-000000000001';const updated='2026-10-09T00:00:00Z';const draft={id,subject:'Synthetic campaign',campaign_type:'user_digest',status:'draft',updated_at:updated,created_at:updated,stats:{sent:0,opened:0,clicked:0,bounced:0}};
const response=(data:unknown,ok=true)=>({ok,json:async()=>data});
beforeEach(()=>{jest.clearAllMocks();mockFetch.mockResolvedValue(response({campaigns:[draft]}));});
test('observed revision submitted, queue acceptance never shown as mailbox delivery',async()=>{render(<NewslettersPage/>);fireEvent.click(await screen.findByText('今すぐ配信'));expect(screen.getByText(/メール到達は別途確認/)).toBeTruthy();mockFetch.mockResolvedValue(response({campaign:{...draft,status:'sending',stats:{delivery_mode:'newsletter_outbox_v1',total:1,queued:1,unconfirmed:0,accepted:0,suppressed:0,failed:0}},message:'送信キューへの受付を確認しました'}));fireEvent.click(screen.getByText('キューに登録する'));await screen.findByText('送信キューへの受付を確認しました');expect(JSON.parse(mockFetch.mock.calls[1][1].body)).toEqual({action:'send',expected_updated_at:updated});expect(screen.getByText(/提供元の受理はメール到達の確認ではありません/)).toBeTruthy();});
test('lost response is visible; same campaign inspect does not resend',async()=>{render(<NewslettersPage/>);fireEvent.click(await screen.findByText('今すぐ配信'));mockFetch.mockRejectedValueOnce(new Error('network'));fireEvent.click(screen.getByText('キューに登録する'));await screen.findByText(/受付結果を確認できません/);mockFetch.mockResolvedValue(response({campaign:draft,receipt:null,message:'受付はまだ確認できません'}));fireEvent.click(screen.getByText('受付状況を確認'));await screen.findByText('受付はまだ確認できません');expect(JSON.parse(mockFetch.mock.calls[2][1].body).action).toBe('inspect');expect(mockFetch.mock.calls.filter(([,o])=>o&&JSON.parse(o.body).action==='send')).toHaveLength(1);});
test('legacy sent statistics expose missing arrival evidence',async()=>{mockFetch.mockResolvedValue(response({campaigns:[{...draft,status:'sent'}]}));render(<NewslettersPage/>);await screen.findByText(/旧方式の記録です/);expect(screen.queryByText(/開封率/)).toBeNull();});
test('initial read failure cannot look like confirmed no campaigns',async()=>{mockFetch.mockRejectedValue(new Error('network'));render(<NewslettersPage/>);await waitFor(()=>expect(screen.getByRole('status').textContent).toContain('受付状況は未確認'));});
