-- 複数メニュー予約の保存（提供前監査 #1 根本対策）
--
-- 事実: 予約UIは「複数選択可」で料金は全メニュー合計・枠も合計時間で確保するのに、bookings は
--   先頭メニュー menu_id しか保存せず、確認メール・台帳・マイページに1件しか出ない。施設は当日
--   2件目の施術を把握できず現場破綻、客は「なぜこの額」となる確定データ欠損だった。
--
-- 対策: bookings に menu_ids（選択した全メニューIDの配列）を追加。primary の menu_id は後方互換・
--   旧データ表示フォールバック用に残す。アプリは予約作成後に menu_ids を保存し、表示側は menu_ids 優先・
--   無ければ menu_id にフォールバックする。RPC のシグネチャは変えない（PostgREST のオーバーロード
--   による曖昧化を避けるため、menu_ids はアプリ側の追記更新で保存する）。
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS menu_ids UUID[];
